
// Simple i18n service
const translations: Record<string, Record<string, string>> = {
  'en': {
    'system.online': 'SYSTEM ONLINE',
    'system.latency': 'LATENCY',
    'nav.dashboard': 'Dashboard',
    'nav.chat': 'Chat',
    'nav.vision': 'Vision',
    'nav.voice': 'Voice',
    'nav.forge': 'Forge',
    'nav.avatar': 'Avatar',
    'nav.theory': 'Theory',
    'nav.discovery': 'Discovery',
    'nav.pro': 'Pro',
    'nav.overlay': 'Overlay',
    'welcome.title': 'KLUTCH',
    'welcome.subtitle': 'GAMING OS',
    'forge.title': 'ASSET FORGE',
    'forge.prompt': 'ENTER PROMPT',
    'forge.generate': 'GENERATE ASSET',
    'forge.generating': 'FORGING...',
    'profile.rank': 'CURRENT RANK',
    'profile.stats': 'COMBAT STATS',
    'vision.title': 'NEXUS VISION',
    'vision.subtitle': 'Upload screenshots. Uncover secrets. Optimize loadouts.',
    'vision.drop': 'DROP SCREENSHOT OR CLICK',
    'vision.analyze': 'ANALYZE VISUAL',
    'vision.analyzing': 'SCANNING...',
    'vision.waiting': 'WAITING FOR VISUAL INPUT...',
    'theory.title': 'THEORYCRAFT ENGINE',
    'theory.subtitle': 'Deep computation for DPS, mechanics, and meta-analysis.',
    'theory.scenario': 'THE PROBLEM (SCENARIO)',
    'theory.data': 'RAW DATA (STATS/ITEMS)',
    'theory.execute': 'EXECUTE ANALYSIS',
    'theory.thinking': 'COMPUTING...',
    'stats.match_logger': 'MATCH LOGGER',
    'stats.log_win': 'LOG VICTORY (+500 XP)',
    'stats.log_loss': 'LOG DEFEAT (+100 XP)',
    'stats.add_kills': 'ADD KILLS',
    'settings.logout': 'LOGOUT SYSTEM',
    'settings.reset': 'RESET ALL DATA',
    'settings.reset_confirm': 'DATA WIPED. REBOOTING...',
    // Auth Translations
    'auth.login_title': 'SYSTEM LOGIN',
    'auth.register_title': 'NEW OPERATIVE',
    'auth.forgot_title': 'RECOVER ACCESS',
    'auth.email': 'EMAIL ADDRESS',
    'auth.username': 'CODENAME (USER)',
    'auth.password': 'PASSPHRASE',
    'auth.btn_login': 'INITIATE UPLINK',
    'auth.btn_register': 'REGISTER ID',
    'auth.btn_recover': 'SEND RECOVERY LINK',
    'auth.switch_register': 'NO ID? REGISTER NOW',
    'auth.switch_login': 'HAVE ID? LOGIN',
    'auth.forgot_pass': 'FORGOT PASSPHRASE?',
    'auth.error_dup': 'ERROR: IDENTITY ALREADY EXISTS IN DATABASE',
    'auth.error_cred': 'ERROR: INVALID CREDENTIALS',
    'auth.error_miss': 'ERROR: MISSING REQUIRED FIELDS',
    'auth.success_reg': 'REGISTRATION COMPLETE. LOGIN REQUIRED.',
    'auth.success_reset': 'RECOVERY LINK SENT TO NEURAL NET.',
  },
  'pt': {
    'system.online': 'SISTEMA ONLINE',
    'system.latency': 'LATÊNCIA',
    'nav.dashboard': 'Início',
    'nav.chat': 'Chat',
    'nav.vision': 'Visão',
    'nav.voice': 'Voz',
    'nav.forge': 'Forge',
    'nav.avatar': 'Avatar',
    'nav.theory': 'Teoria',
    'nav.discovery': 'Descobrir',
    'nav.pro': 'Pro',
    'nav.overlay': 'Overlay',
    'welcome.title': 'KLUTCH',
    'welcome.subtitle': 'SISTEMA GAMER',
    'forge.title': 'FORJA DE ASSETS',
    'forge.prompt': 'DIGITE O PROMPT',
    'forge.generate': 'GERAR ASSET',
    'forge.generating': 'FORJANDO...',
    'profile.rank': 'RANK ATUAL',
    'profile.stats': 'ESTATÍSTICAS',
    'vision.title': 'VISÃO NEXUS',
    'vision.subtitle': 'Carregue prints. Descubra segredos. Otimize builds.',
    'vision.drop': 'ARRASTE A IMAGEM OU CLIQUE',
    'vision.analyze': 'ANALISAR VISUAL',
    'vision.analyzing': 'ESCANEANDO...',
    'vision.waiting': 'AGUARDANDO ENTRADA VISUAL...',
    'theory.title': 'MOTOR THEORYCRAFT',
    'theory.subtitle': 'Computação profunda para DPS, mecânicas e meta-análise.',
    'theory.scenario': 'O PROBLEMA (CENÁRIO)',
    'theory.data': 'DADOS BRUTOS (STATUS/ITENS)',
    'theory.execute': 'EXECUTAR ANÁLISE',
    'theory.thinking': 'COMPUTANDO...',
    'stats.match_logger': 'REGISTRAR PARTIDA',
    'stats.log_win': 'REGISTRAR VITÓRIA (+500 XP)',
    'stats.log_loss': 'REGISTRAR DERROTA (+100 XP)',
    'stats.add_kills': 'ADICIONAR KILLS',
    'settings.logout': 'SAIR DA CONTA',
    'settings.reset': 'RESETAR DADOS DE FÁBRICA',
    'settings.reset_confirm': 'DADOS APAGADOS. REINICIANDO...',
    // Auth Translations
    'auth.login_title': 'LOGIN DO SISTEMA',
    'auth.register_title': 'NOVO OPERADOR',
    'auth.forgot_title': 'RECUPERAR ACESSO',
    'auth.email': 'ENDEREÇO DE EMAIL',
    'auth.username': 'NOME DE USUÁRIO',
    'auth.password': 'SENHA DE ACESSO',
    'auth.btn_login': 'INICIAR CONEXÃO',
    'auth.btn_register': 'REGISTRAR ID',
    'auth.btn_recover': 'ENVIAR LINK DE RECUPERAÇÃO',
    'auth.switch_register': 'SEM CONTA? REGISTRE-SE',
    'auth.switch_login': 'JÁ TEM CONTA? ENTRAR',
    'auth.forgot_pass': 'ESQUECEU A SENHA?',
    'auth.error_dup': 'ERRO: USUÁRIO OU EMAIL JÁ EXISTEM NO BANCO DE DADOS',
    'auth.error_cred': 'ERRO: CREDENCIAIS INVÁLIDAS',
    'auth.error_miss': 'ERRO: PREENCHA TODOS OS CAMPOS',
    'auth.success_reg': 'REGISTRO COMPLETO. FAÇA LOGIN.',
    'auth.success_reset': 'LINK DE RECUPERAÇÃO ENVIADO PARA O EMAIL.',
  }
};

export const getLanguage = (): string => {
  const lang = navigator.language.split('-')[0];
  return ['pt', 'en'].includes(lang) ? lang : 'en';
};

export const t = (key: string): string => {
  const lang = getLanguage();
  return translations[lang][key] || translations['en'][key] || key;
};
